### PR TITLE
ci: check secrets

### PR DESCRIPTION
**Pull request by thelukewalton**

### CODE REVIEW

**Comment by thelukewalton** [comment]
Comment!

**Comment by thelukewalton** [comment]
hi \n test

**Comment by thelukewalton** [comment]
hi  test

**Comment by thelukewalton** [comment]
hi </br> test

**Comment by thelukewalton** [comment]
<en>hi</en> <strong> strong!</strong> <b>BBB</b> other </br> test

**Review by mikecoomber — APPROVED** [review]

**Pull request merged**
